@k8 = https://XXX.app.commissions.cloud.sap
@clientid = 
@clientsecret = 
@ias = https://xxxxx.accounts.ondemand.com


# @name login
POST {{ias}}/oauth2/token?grant_type=client_credentials
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{clientid}}:{{clientsecret}}

###
@accessToken = {{login.response.body.access_token}}

###
GET {{k8}}/mtsvc/tcmp/rest/v2/participants
Authorization: Bearer {{accessToken}}

###
GET {{k8}}/mtsvc/tcmp/rest/v2/positions
Authorization: Bearer {{accessToken}}

###
GET {{k8}}/mtsvc/tcmp/rest/v2/titles
Authorization: Bearer {{accessToken}}

###
GET {{k8}}/mtsvc/tcmp/rest/v2/positionRelationShips
Authorization: Bearer {{accessToken}}

###
GET {{k8}}/mtsvc/tcmp/rest/v2/positionRelationTypes
Authorization: Bearer {{accessToken}}

###
GET {{k8}}/mtsvc/tcmp/rest/v2/plans
Authorization: Bearer {{accessToken}}

###
GET {{k8}}/mtsvc/tcmp/rest/v2/plans?$filter=name eq 'Manager Plan'&expand=calendar
Authorization: Bearer {{accessToken}}

###
GET {{k8}}/mtsvc/tcmp/rest/v2/planComponents
Authorization: Bearer {{accessToken}}

###
GET {{k8}}/mtsvc/tcmp/rest/v2/rules
Authorization: Bearer {{accessToken}}

###
GET {{k8}}/mtsvc/tcmp/rest/v2/formulas
Authorization: Bearer {{accessToken}}

###
GET {{k8}}/mtsvc/tcmp/rest/v2/fixedValues
Authorization: Bearer {{accessToken}}

###
GET {{k8}}/mtsvc/tcmp/rest/v2/variables
Authorization: Bearer {{accessToken}}

###
GET {{k8}}/mtsvc/tcmp/rest/v2/variableAssignments
Authorization: Bearer {{accessToken}}

###
GET {{k8}}/mtsvc/tcmp/rest/v2/territories
Authorization: Bearer {{accessToken}}

###
GET {{k8}}/mtsvc/tcmp/rest/v2/rateTables
Authorization: Bearer {{accessToken}}

###
GET {{k8}}/mtsvc/tcmp/rest/v2/relationalMDLTs
Authorization: Bearer {{accessToken}}

###
GET {{k8}}/mtsvc/tcmp/rest/v2/relationalMDLTs?$filter=name eq 'LT_GERMANY'
Authorization: Bearer {{accessToken}}

###
GET {{k8}}/mtsvc/tcmp/rest/v2/salesOrders
Authorization: Bearer {{accessToken}}
Accept-Language: en-US
Content-Type: application/json

###
GET {{k8}}/mtsvc/tcmp/rest/v2/salesTransactions
Authorization: Bearer {{accessToken}}
Accept-Language: en-US
Content-Type: application/json

###
GET {{k8}}/mtsvc/tcmp/rest/v2/transactionAssignments
Authorization: Bearer {{accessToken}}
Accept-Language: en-US
Content-Type: application/json

###
GET {{k8}}/mtsvc/tcmp/rest/v2/credits
Authorization: Bearer {{accessToken}}
Accept-Language: en-US
Content-Type: application/json

###
GET {{k8}}/mtsvc/tcmp/rest/v2/credits?$filter=period/periodSeq eq 2533274790396049&inlineCount=true
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
GET {{k8}}/mtsvc/tcmp/rest/v2/measurements?$filter=period/periodSeq eq 2533274790396049&inlineCount=true
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
GET {{k8}}/mtsvc/tcmp/rest/v2/measurements
Authorization: Bearer {{accessToken}}
Accept-Language: en-US
Content-Type: application/json

###
GET {{k8}}/mtsvc/tcmp/rest/v2/primaryMeasurements
Authorization: Bearer {{accessToken}}
Accept-Language: en-US
Content-Type: application/json

###
GET {{k8}}/mtsvc/tcmp/rest/v2/secondaryMeasurements
Authorization: Bearer {{accessToken}}
Accept-Language: en-US
Content-Type: application/json

###
GET {{k8}}/mtsvc/tcmp/rest/v2/incentives
Authorization: Bearer {{accessToken}}
Accept-Language: en-US
Content-Type: application/json

###
GET {{k8}}/mtsvc/tcmp/rest/v2/commissions
Authorization: Bearer {{accessToken}}
Accept-Language: en-US
Content-Type: application/json


###
GET {{k8}}/mtsvc/tcmp/rest/v2/deposits
Authorization: Bearer {{accessToken}}
Accept-Language: en-US
Content-Type: application/json


###
GET {{k8}}/mtsvc/tcmp/rest/v2/payments?expand=payee,position,period,processingUnit
Authorization: Bearer {{accessToken}}
Accept-Language: en-US
Content-Type: application/json

###
GET {{k8}}/mtsvc/tcmp/rest/v2/balances
Authorization: Bearer {{accessToken}}
Accept-Language: en-US
Content-Type: application/json

#### ,processingUnit,position,period&skip=0&top=1
GET {{k8}}/mtsvc/tcmp/rest/v2/appliedDeposits
Authorization: Bearer {{accessToken}}
Accept-Language: en-US
Content-Type: application/json


GET {{k8}}/mtsvc/tcmp/rest/v2/calendars
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
GET {{k8}}/mtsvc/tcmp/rest/v2/calendarService/defaultPeriod
Content-Type: application/json
Authorization: Bearer {{accessToken}}




###
GET {{k8}}/mtsvc/tcmp/rest/v2/paymentMappings
Authorization: Bearer {{accessToken}}
Accept-Language: en-US
Content-Type: application/json


###  Undocumented APIS
GET {{k8}}/mtsvc/tcmp/rest/v2/globalFieldNames
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
POST {{k8}}/mtsvc/tcmp/rest/v2/globalFieldNames
Content-Type: application/json
Authorization: Bearer {{accessToken}}

[
    {
        "name": "userId",
        "description": "created using API V2",
        "globalFieldNameDataTypeLength": "10"
    },
    {
        "name": "externalUserId",
        "description": "created using API V2",
        "globalFieldNameDataTypeLength": "10"
    }
]

###  Undocumented APIS
GET {{k8}}/mtsvc/tcmp/rest/v2/paymentMappings
Content-Type: application/json
Authorization: Bearer {{accessToken}}


###
POST {{k8}}/mtsvc/tcmp/rest/v2/paymentMappings
Content-Type: application/json
Authorization: Bearer {{accessToken}}

[
    {
        "sourceTableName": "CS_Participant",
        "globalFieldName": "userId",
        "paymentAttribute": "genericAttribute2",
        "sourceAttribute": "userId"
    },
    {
        "sourceTableName": "CS_Participant",
        "globalFieldName": "externalId",
        "paymentAttribute": "genericAttribute3",
        "sourceAttribute": "genericAttribute2"
    }
]

